version: '3.8'

services:
  classifier-api:
    build: .
    image: cats-dogs-classifier:latest
    container_name: cats_dogs_api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=models/final_cnn_model.h5
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
